volume = 1.0
maxPlayCont = 8
spatial = true
sampleRate = 44100
useYoutubeDownloader = true
relayServerURL = "https://raw.githubusercontent.com/TeamFelnull/IamMusicPlayer/master/relay_server.json"
lavaPlayerNativesURL = "https://raw.githubusercontent.com/Mod-Sauce/test_lavaplayer_IMP/refs/heads/main/lavaplayer/natives_link.json"
maxWaitTime = 10000
retryTime = 3000
dropItemRing = true
patchouliIntegration = true
soundPhysicsRemasteredIntegration = true
showMusicLines = false
showSpeakerRange = false
